name: Update readme with blog posts
on:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v1
        with:
<<<<<<< Updated upstream
          feed-url: https://tiffanywhite.dev/rss/
=======
          feed-url: https://www.tiffanywhite.dev/rss/
>>>>>>> Stashed changes
          readme-section: feed

      - uses: JasonEtco/rss-to-readme@v1
        with:
<<<<<<< Updated upstream
          feed-url: https://buttondown.email/tiffanywhite/rss
=======
          feed-url: https://news.tiffanywhite.dev/rss
>>>>>>> Stashed changes
          readme-section: newsletters
          
